[package]
name = "governance_contract"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]
doctest = false

[dependencies]
soroban-sdk = "22.0.8"

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
